global: 
  scrape_interval: 20s
  evaluation_interval: 20s

#attach the below label for graph view
  external_labels:
    monitor: 'Docker-pk-monitor'

#end poinds for scrape
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 20s
    static_configs:
    - targets: ['cadvisor:8080']
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "container.rules"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
